// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
import type { UiLocale } from '$lib/i18n/locales';

declare global {
	namespace App {
		// interface Error {}
		interface Locals {
			locale: UiLocale;
		}
		interface PageData {
			locale: UiLocale;
		}
		// interface PageState {}
		interface Platform {
			// `Env` (DB: D1Database) comes from worker-configuration.d.ts, generated by
			// `wrangler types` from wrangler.jsonc's own `d1_databases` binding — regenerate that
			// file (not this one) whenever a binding is added/changed, per wrangler's own reminder.
			env: Env;
			cf?: CfProperties;
			ctx: ExecutionContext;
		}
	}
	// vite.config.ts's own `define` — true only for `BUILD_TARGET=capacitor` builds. See that
	// file's own comment for why /shopping-list specifically needs this at the client level.
	const __IS_CAPACITOR__: boolean;
}

export {};
